name: Build

on:
  push:
    branches: [ main ]
    paths:
      - 'Cargo.toml'
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Cargo.toml'
      - 'src/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
